version: "3.7"
services:
    app:
        image: "lnlscon/utility:v2.0"
        build: "."
        volumes:
            - "./Redes e Beaglebones.xlsx:/opt/spreadsheet/Redes e Beaglebones.xlsx:ro"
        ports:
            - 8080:80
